name = "AugmentedMixing"
uuid = "73c46ca0-0a9b-4359-b09e-d5c0842a0574"
authors = ["Jan Schwiddessen <jan.schwiddessen@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DoubleFloats = "1.4.3"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
Printf = "1.11.0"
Random = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.11"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DoubleFloats", "Random", "Test"]
